### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by fabiankessler**
Dear Miguel, 

Your completely library looks very promising for my needs. As I progress in understanding the internals and as I try to make it work for my use case, I'll commit small changes, that is:
- explanations in javadoc
- more tests and examples
- small syntax improvements

Take from it what you like.

Although I'd favor a more strict approach to handling null (not allowing it as input), I won't commit such changes.

I also plan to create tasks in the issue tracker. Not just for bugs (haven't found any), also for discussing how things could be changed. If you don't like that, please let me know.

My use case in short: 
- large list of terms (over a million)
- custom sorting

### CODE REVIEW

**Comment by fmmfonseca** [comment]
Hi Fabian,

Thank you for using the library, and for the feedback!
I will take a look at your propositions, a couple of quick comments:

* Last time I tried to use the diamond operator there were one or two cases where the compiler still needed it, and for me its a case of all or nothing, so I will double check if that's still the case.
* The absence of default implementations of the Indexable interface is intentional. The implementation possibilities are endless and are better left to the client.
* The null search indeed doesn't make sense, since the Index interface doesn't allow null key's anyway.
* The premature return in the search is a viable optimisation.
* The absence of a combined Analyzer is intentional as well as the interface is inherently composable by design:
      
```java
private static class SampleAnalyzer extends Analyzer
{
    private Analyzer tokenizer = new WordTokenizer();
    private Analyzer transformer = new LowerCaseTransformer();
    private Analyzer filter = new LengthFilter(3, 100);

    @Override
    public Collection<String> apply(Collection<String> input)
    {
        return filter.apply(tokenizer.apply(transformer.apply(input)));
    }
}
```

* The enhancement of sorting logic is something I have considered before but I'm not sure about the implementation yet. My first thought was to have the Index implementations return a SearchResult wrapper with a match score, and have the AutocompleteEngine sort/trim/unwrap it.

**Comment by fabiankessler** [comment]
Nice. 
You may want to deny this pull request, and maybe take some parts yourself?

The library is already very powerful, it does more than I first thought. What it needs is more documentation, more examples (I can help with those), and then more users.

Where do you want to have examples and use cases added? It can be in the sample module. Or in the core module in the form of (more complex) tests, one per class. Or another module called 'integrationtests'. I imagine a large text file with words to be used in the samples/tests, then tests for different use cases (fuzzy/exact searches, starts-with vs full string, different analyzers, analyzer chaining...) I believe it helps a lot to see such examples to copy paste as a start. And at the same time they can assert that things work correctly.

**Comment by fmmfonseca** [comment]
Fabian, again thanks for the feedback. I will surely integrate some of your suggestions in one way or another. Meanwhile if you have any questions just shoot.

**Comment by fmmfonseca** [comment]
Some of the suggestions are now implemented in version 0.3.0

**Pull request closed without merging**
